package djf.settings;

/**
 * This enum provides properties that are to be loaded via
 * XML files to be used for setting up the application.
 * 
 * @author Richard McKenna
 * @version 1.0
 */
public enum AppPropertyType {
    // LOADED FROM app_properties.xml

    // INITIAL WINDOW TITLE AND LOGO
    APP_TITLE,
    APP_LOGO,
    APP_ABOUT_TITLE,
    APP_DESCRIBE,
    
    // FOR FINDING THE CSS FILE
    APP_CSS,
    APP_PATH_CSS,

    // FILE TOOLBAR ICONS
    NEW_ICON,
    LOAD_ICON,
    SAVE_ICON,
    SAVE_AS_ICON,
    EXPORT_ICON,
    EXIT_ICON,
    UNDO_BUTTON_TEXT,
    REDO_BUTTON_TEXT,
    ABOUT_BUTTON_TEXT,
        
    // FILE TOOLBAR TOOLTIPS FOR BUTTONS
    NEW_TOOLTIP,
    LOAD_TOOLTIP,
    SAVE_TOOLTIP,
    SAVE_AS_TOOLTIP,
    EXPORT_TOOLTIP,
    EXIT_TOOLTIP,
    UNDO_TOOLTIP,
    REDO_TOOLTIP,
    ABOUT_TOOLTIP,
    
    // TAB PANE
    COURSE_TAB_TEXT,
    TA_TAB_TEXT,
    REC_TAB_TEXT,
    SCHEDULE_TAB_TEXT,
    PROJECT_TAB_TEXT,
    
    // Add, edit, clear, update button text
    ADD_BUTTON_TEXT,
    EDIT_BUTTON_TEXT,
    CLEAR_BUTTON_TEXT,
    UPDATE_BUTTON,
    
    // ERROR MESSAGES AND TITLES FOR DIALOG BOXES
    NEW_ERROR_MESSAGE,
    NEW_ERROR_TITLE,
    LOAD_ERROR_MESSAGE,
    LOAD_ERROR_TITLE,
    SAVE_ERROR_MESSAGE,
    SAVE_ERROR_TITLE,
    PROPERTIES_LOAD_ERROR_MESSAGE,
    PROPERTIES_LOAD_ERROR_TITLE,
	
    // AND VERIFICATION MESSAGES AND TITLES
    NEW_COMPLETED_MESSAGE,
    NEW_COMPLETED_TITLE,
    LOAD_COMPLETED_MESSAGE,
    LOAD_COMPLETED_TITLE,
    SAVE_COMPLETED_MESSAGE,
    SAVE_COMPLETED_TITLE,	
    SAVE_UNSAVED_WORK_TITLE,
    SAVE_UNSAVED_WORK_MESSAGE,
    SAVE_WORK_TITLE,
    LOAD_WORK_TITLE,

    // DATA FILE EXTENSIONS AND DESSCRIPTIONS
    WORK_FILE_EXT,
    WORK_FILE_EXT_DESC,
    
    // Recitation Error mess
    REC_SECTION_MISS,
    REC_SECTION_MISS_MESS,
    REC_TIME_MISS,
    REC_TIME_MISS_MESS,
    REC_LOCATION_MISS,
    REC_LOCATION_MISS_MESS,
    
    REC_SECTION_UNIQUE,
    REC_SECTION_UNIQUE_MESS,
    
    // Schedule Error mess
    SCHEDULE_TYPE_MISS,
    SCHEDULE_TYPE_MISS_MESS,
    SCHEDULE_DATE_MISS,
    SCHEDULE_DATE_MISS_MESS,
    
    // Projects Error mess
    TEAM_NAME_MISS,
    TEAM_NAME_MISS_MESS,
    TEAM_COLOR_MISS,
    TEAM_COLOR_MISS_MESS,
    TEAM_TEXTCOLOR_MISS,
    TEAM_TEXTCOLOR_MISS_MESS,
    TEAM_LINK_MISS,
    TEAM_LINK_MISS_MESS,
    TEAM_UNIQUE,
    TEAM_UNIQUE_MESS,
    STUDENT_FIRSTNAME_MISS,
    STUDENT_FIRSTNAME_MISS_MESS,
    STUDENT_LASTNAME_MISS,
    STUDENT_LASTNAME_MISS_MESS,
    STUDENT_TEAM_MISS,
    STUDENT_TEAM_MISS_MESS,
    STUDENT_ROLE_MISS,
    STUDENT_ROLE_MISS_MESS
    
}
