
package sm;

/**
 *
 * @author trungvo
 */
public enum ScheduleManagerProp {
    SCHEDULE_TITLE,
    CALENDAR_LABEL,
    START_MON_LABEL,
    END_FRI_LABEL,
    SCHEDULE_LABEL,
    TYPE_TABLECOLUMN,
    DATE_TABLECOLUMN,
    TITLE_TABLECOLUMN,
    TOPIC_TABLECOLUMN,
    SCHE_ADDEDIT_LABEL,
    TYPE_LABEL,
    DATE_LABEL,
    TIME_LABEL,
    TITLE_LABEL,
    TOPIC_LABEL,
    LINK_LABEL,
    CRITERIA_LABEL,
    SCHE_ADDUPDATE_BUTTON,
    SCHE_CLEAR_BUTTON,
    
    // promt text in TF
    TIME_PROMPT_TEXT,
    TITLE_PROMPT_TEXT,
    TOPIC_PROMPT_TEXT,
    LINK_PROMPT_TEXT,
    CRITERIA_PROMPT_TEXT
}
