
package rm;

/**
 *
 * @author trungvo
 */
public enum RecManagerProp {
    RECITATION_TITLE,
    RECITATION_SECTION_TABLECOLUMN,
    RECITATION_INSTRUCTOR_TABLECOLUMN,
    RECITATION_DAYTIME_TABLECOLUMN,
    RECITATION_LOCATION_TABLECOLUMN,
    RECITATION_TA_TABLECOLUMN,
    RECITATION_ADDEDIT_LABEL,
    RECITATION_SECTION_LABEL,
    RECITATION_INSTRUCTOR_LABEL,
    RECITATION_DAYTIME_LABEL,
    RECITATION_LOCATION_LABEL,
    RECITATION_TA_LABEL,
    RECITATION_ADDUPDATE_BUTTON,
    RECITATION_CLEAR_BUTTON,
    
    // Promt text in TF
    SECTION_PROMPT_TEXT,
    INSTRUCTOR_PROMPT_TEXT,
    DAYTIME_PROMPT_TEXT,
    LOCATION_PROMPT_TEXT,
    TA_PROMPT_TEXT,
    
    // TOOLTIP
    DELETE_TOOLTIP
}
